/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package modelo;

/**
 *
 * @author catax
 */
public class frmArticulos extends javax.swing.JInternalFrame {

    /**
     * Creates new form Articulos
     */
    public frmArticulos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnListado = new javax.swing.JPanel();
        pnMantenimiento = new javax.swing.JPanel();

        javax.swing.GroupLayout pnListadoLayout = new javax.swing.GroupLayout(pnListado);
        pnListado.setLayout(pnListadoLayout);
        pnListadoLayout.setHorizontalGroup(
            pnListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 637, Short.MAX_VALUE)
        );
        pnListadoLayout.setVerticalGroup(
            pnListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 362, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Listado", pnListado);

        javax.swing.GroupLayout pnMantenimientoLayout = new javax.swing.GroupLayout(pnMantenimiento);
        pnMantenimiento.setLayout(pnMantenimientoLayout);
        pnMantenimientoLayout.setHorizontalGroup(
            pnMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 637, Short.MAX_VALUE)
        );
        pnMantenimientoLayout.setVerticalGroup(
            pnMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 362, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Mantenimiento", pnMantenimiento);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel pnListado;
    private javax.swing.JPanel pnMantenimiento;
    // End of variables declaration//GEN-END:variables
}
